In [2]:
import numpy as np
print(np.__version__)

2.2.0


In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# Q: creat 3*3 numpy array of all True's
#np.array([[1,1,1],[1,1,1],[1,1,1]])
np.full((3,3),True,dtype=bool)
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# Q: extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
#Q: replace all odd numbers in arr with -1 
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# for i in arr:
#     if i%2==1:
#         arr[i] = -1
# arr        
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
#Q: replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
out = np.where(arr%2==1,-1,arr)

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x