In [2]:
import numpy as np
print(np.__version__)

2.2.0


In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# Q: creat 3*3 numpy array of all True's
#np.array([[1,1,1],[1,1,1],[1,1,1]])
np.full((3,3),True,dtype=bool)
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# Q: extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
#Q: replace all odd numbers in arr with -1 
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# for i in arr:
#     if i%2==1:
#         arr[i] = -1
# arr        
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
#Q: replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
out = np.where(arr%2==1,-1,arr)

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Q: convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr =arr.reshape(2,5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

# stack a and b horizontally
np.hstack([a,b])
# stack a and b vertically
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Sum along axis 0 (column-wise)
print(np.sum(arr, axis=0))  # Output: [12 15 18]

# Sum along axis 1 (row-wise)
print(np.sum(arr, axis=1))  # Output: [ 6 15 24]


[12 15 18]
[ 6 15 24]


In [ ]:
# 10 : Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#np.r_ : connect arrays row-wise
#np.repeat : repeat elements of an array
#np.tile : construct an array by repeating A the number of times given by reps
a = np.array([3,6,9])
b = np.r_[np.repeat(a,3),np.tile(a,3)]

b


array([3, 3, 3, 6, 6, 6, 9, 9, 9, 3, 6, 9, 3, 6, 9, 3, 6, 9])

In [ ]:
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

# for i in a :
#     if a[i]==b[i]:
#         c = a[i]
#tlqkf~! 

# Q : Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)
# 1d means 1 dimension

array([2, 4])

In [ ]:
#Q : From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c = np.intersect1d(a,b)
d = np.setdiff1d(a,b)
d


array([1, 2, 3, 4])

`problem 14`

In [1]:
#Q : get all items between 5 and 10 from a
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index =np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

In [11]:
#Q15 : Convert the function maxx that works on two scalars, to work on two arrays.
import numpy as np
# def pair_max(a,b):
#     c = np.array([])
#     for i in a:
#         for j in b:
#             if i>j:
#                 c[i] = a[i]
#             else:
#                 c[j] = b[j]
#     return c 

# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])

# pair_max(a,b)
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# np.maximum(a,b)
#---------------------------------------------------
def maxx(x, y): 
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y   

a= np.array([5, 7, 9, 8, 6, 4, 5])
b= np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes = [str])     
pair_max(a, b)

            

array(['6', '7', '9', '8', '9', '7', '5'], dtype='<U1')

`problem 16: Swap columns 1 and 2 in the array`

In [18]:
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[:,[1,0,2]]
arr




[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

`problem 17: Swap rows 1 and 2 in the array`

In [22]:
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)
arr =arr[[1,0,2],:]
#Print all columns of the first row, then print all columns of the zeroth row,
# and finally print all columns of the second row
print(arr)




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


`problem 18-1`

In [34]:
import numpy as np

n = 3
arr = np.arange(9).reshape(n, n)
tmp = np.zeros((n, n))  # 임시 배열 생성
print("Original array:")
print(arr)

# 배열을 반전시키는 코드 (tmp 사용)
for i in range(n):
    tmp[i] = arr[i]           # arr의 i번째 행을 tmp에 복사

for i in range(3):
    arr[i] = tmp[n-i-1]       # arr의 i번째 행을 arr의 반대 위치로 변경

print("Reversed array:")
print(arr)


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed array:
[[6 7 8]
 [3 4 5]
 [0 1 2]]


`problem18-2`